

name: Java CI with Maven for Ecommerce Tests

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Install Google Chrome 
      run: |
        sudo apt install chromium-browser
    - name: Ecommerce tests execution
      run: mvn -B -f pom.xml clean test
