on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Install Google Chrome 
      run: |
        VERSION="114.0.5735.90"
        sudo apt install ./google-chrome-stable_current_amd64.deb
        wget "https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${VERSION}-1_amd64.deb" -O google-chrome-stable_${VERSION}-1_amd64.deb
        sudo apt install ./google-chrome-stable_${VERSION}-1_amd64.deb
    - name: Install Chromedriver
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip
        wget -N https://chromedriver.storage.googleapis.com/$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip -P ~/
        unzip ~/chromedriver_linux64.zip -d ~/
        sudo mv -f ~/chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver
    - name: Log ChromeDriver version
      run: chromedriver --version
    - name: Log Chrome version
      run: google-chrome --version
    - name: Ecommerce tests execution
      run: mvn -B -f pom.xml clean test
